# @name login
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "douglasdev.cn@gmail.com",
  "password": 1234
}
###

@authToken = {{login.response.body.$.access_token}}

@endpoint = /support-chats

#### 1) Get all support chats
GET {{url}}{{endpoint}}
Authorization: Bearer {{authToken}}

#### 2) Send a message
POST {{url}}{{endpoint}}/send-message
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "to": "user@example.com",
  "message": "Hello, this is a test message."
}

#### 3) Get support chat by ID
GET {{url}}{{endpoint}}/messages/1
Authorization: Bearer {{authToken}}