# @name login
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "douglasdev.cn@gmail.com",
  "password": 1234
}
###

@authToken = {{login.response.body.$.access_token}}

@endpoint = /clients

#### 1) Get all clients
GET {{url}}{{endpoint}}
Authorization: Bearer {{authToken}}

#### 2) Get client by id
GET {{url}}{{endpoint}}/3
Authorization: Bearer {{authToken}}

#### 3) Add new client
POST {{url}}{{endpoint}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "nome": "MegaMix",
  "contacts":[
    {
      "name": "Ariel",
      "phone": "64984550047"
    },
    {
      "name": "Eduardo"
    }
  ]
}

#### 4) Update client
PATCH {{url}}{{endpoint}}/8
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "nome": "MegaMix",
  "contacts":[
    {
      "name": "Ariel",
      "phone": "64984550047"
    },
    {
      "name": "Eduardo"
    }
  ]
}

#### 5) Delete client
DELETE {{url}}{{endpoint}}/5
Authorization: Bearer {{authToken}}
