# @name login
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "douglasdev.cn@gmail.com",
  "password": 1234
}
###

@authToken = {{login.response.body.$.access_token}}

@endpoint = /atendimentos


#### 1) Get all atendimentos
GET {{url}}{{endpoint}}
Authorization: Bearer {{authToken}}

#### 2) Get atendimento by id
GET {{url}}{{endpoint}}/5
Authorization: Bearer {{authToken}}

#### 3) Get atendimento by user id
GET {{url}}{{endpoint}}/get_by_user/1
Authorization: Bearer {{authToken}}

#### 4) Get all atendimentos status
GET {{url}}{{endpoint}}/status
Authorization: Bearer {{authToken}}
