# @name login
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "douglasdev.cn@gmail.com",
  "password": 1234
}
###

@authToken = {{login.response.body.$.access_token}}

@endpoint = /auth

POST {{url}}{{endpoint}}/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEiLCJzdWIiOjEsImlkIjoxLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc0MTUzMjczMSwiZXhwIjoxNzQxNTYxNTMxfQ.uwF2-lDU0JRgu72YlAFCboMYgxqVOxGX1KrDsJ1dKXE"
}